variable "public_subnet_1_id" {}
variable "public_subnet_2_id" {}
variable "private_subnet_1_id" {}
variable "private_subnet_2_id" {}
variable "private_subnet_3_id" {}
variable "private_subnet_4_id" {}
variable "vpc_id" {}
variable "igw_id" {}
variable "project_name" {}